language: python
sudo: false
matrix:
  include:
    - os: linux
      dist: jessie
      python: "3.6"
    - os: linux
      dist: trusty
      python: "2.7"
addons:
  apt:
    packages:
      - python-commandnotfound
      - python3-commandnotfound
