language: python
sudo: false
matrix:
  include:
    - os: linux
      dist: jessie
      python: "3.6"
    - os: linux
      dist: trusty
      python: "2.7"
    - os: osx
      env: FORMULA="python"
      language: generic
    - os: osx
      env: FORMULA="python3"
      language: generic
