language: python
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      python: "3.6"
    - os: linux
      dist: trusty
      python: "3.5"
    - os: linux
      dist: trusty
      python: "3.4"
    - os: linux
      dist: trusty
      python: "3.3"
    - os: linux
      dist: trusty
      python: "2.7"
    - os: osx
      env: FORMULA="python"
      language: generic
    - os: osx
      env: FORMULA="python3"
      language: generic
